### ISSUE TITLE
Adaptation for Trino

### ISSUE THREAD

**Issue by Mihai-CMM** [foursquare/h3-presto#22]
Hello,
One of my devs wants to use the H3 geo  and seeing your project I would like them to do the computations and aggregations directly on Trino 
I am no Java developer and have no clue about Maven. What would need to be done to be able to use it with Trino, I saw trino uses the same folder structure for plugins so will it be enough to move the Jar on that place? And where can i find the Jar or is this something that i need to build by myself 

Thank you

**Comment by isaacbrodsky** [comment]
Hi -- Unfortunately at the moment there is not an official prebuilt jar file. You will need to build it yourself, by install jdk and maven and then running:

```
mvn clean package -DskipTests
```

I'm not familiar with Trino plugins vs Presto plugins, but if it is compatible with Presto plugins (same underlying database engine) then I expect that moving the plugin into the `plugin/h3` directory should work.

**Comment by Mihai-CMM** [comment]
Ok  - thank you
